import Navbar from "./componends/navbar";
import "./globals.css";

export const metadata = {
  title: "Kaffeemaschine",
  description: "Generated by Prattes Felix and Sabine Kollegger",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-bg_creme">
      <body>{children}</body>
    </html>
  );
}
